const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const INTERNAL_SERVER_ERROR = 500;
const CONFLICT = 409;

const UNAUTHORIZED_ERROR_MESSAGE = 'Необходима авторизация';
const INCORRECT_LOGIN = 'Неправильные почта или пароль';

module.exports = {
  BAD_REQUEST,
  NOT_FOUND,
  INTERNAL_SERVER_ERROR,
  UNAUTHORIZED,
  FORBIDDEN,
  CONFLICT,
  UNAUTHORIZED_ERROR_MESSAGE,
  INCORRECT_LOGIN,
};
